name: CI Workflow

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-typos:
    name: typos-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: typos-action
      uses: crate-ci/typos@v1.22.7
      with:
        paths: .lib/

  build:
    name: flutter-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze Dart
      uses: zgosalvez/github-actions-analyze-dart@v3.0.3
