name: CI Workflow

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Shemnei/reviewdog-action-typos@v0.12.1
        with:
          reporter: github-check
          level: warning
          fail_on_error: false
          files: |
            ./lib
          locale: en-gb

  build:
    name: flutter-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze Dart
      uses: zgosalvez/github-actions-analyze-dart@v3.0.3
