name: Dart analysis

on:
  pull_request:

jobs:
  build:
    name: flutter-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: flutter format --set-exit-if-changed

      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v3.0.3

      - name: Build apk
        run: flutter build apk

      - name: Release apk
        if: github.base_ref == 'main'
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
