name: CI Workflow

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v3.0.3

      - name: Build apk
        run: flutter build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk

  versioning:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.VERSIONING }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get current version from file
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ env.VERSION }}
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$2 += 1; print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo $NEW_VERSION > version.txt

      - name: Commit and tag version
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.VERSIONING }}@github.com/${{ github.repository }}
          git add version.txt
          git commit -m "Increment version to ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)


  create-release:
    runs-on: ubuntu-latest
    needs: [build, versioning]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Download APK Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: apk
          path: build/app/outputs/apk/release

      - name: Download Version Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: version
          path: .

      - name: Create Release
        if: github.base_ref == 'main'
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: build/app/outputs/apk/release/app-release.apk
          tag_name: ${{ env.NEW_VERSION }}
          name: "Release ${{ env.NEW_VERSION }}"

      - name: Create Pre-Release
        if: github.base_ref == 'development'
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: build/app/outputs/apk/release/app-release.apk
          tag_name: ${{ env.NEW_VERSION }}
          name: "Pre-Release ${{ env.NEW_VERSION }}"
          prerelease: true
