name: Delete branches after merge
 
on:
  pull_request:
    types: [closed]
 
jobs:
  delete_merged_branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@1.4.3
        with:
         exclude: development          
