name: Typos check

on:
  push:

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Typos check
        uses: Shemnei/reviewdog-action-typos@v0.12.1
        with:
          reporter: github-check
          level: error
          fail_on_error: false
          files: |
            ./lib
          locale: en-gb

  
